// GENERATED by scripts/crop-photos.py: which crop photos exist, and their credits (Wikimedia Commons).
export type PhotoCredit = { file: string; url: string; license: string; author: string };
export const PHOTOS: Record<string, PhotoCredit> = {
 "wheat": {
  "file": "Wheat close-up.JPG",
  "url": "https://commons.wikimedia.org/wiki/File:Wheat_close-up.JPG",
  "license": "CC BY-SA 3.0",
  "author": "User:Bluemoose"
 },
 "maize": {
  "file": "Ab food 06.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Ab_food_06.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Andrey Butko"
 },
 "barley": {
  "file": "Barley grains 4.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Barley_grains_4.jpg",
  "license": "CC BY-SA 2.0 kr",
  "author": "국립국어원"
 },
 "paddy": {
  "file": "Oryza sativa MHNT.BOT.2015.2.52.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Oryza_sativa_MHNT.BOT.2015.2.52.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Roger Culos"
 },
 "jowar": {
  "file": "Sorghum bicolor Moderne MHNT.BOT.2015.34.152.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Sorghum_bicolor_Moderne_MHNT.BOT.2015.34.152.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Roger Culos"
 },
 "chana": {
  "file": "Soaked and dried chickpeas.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Soaked_and_dried_chickpeas.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Tiia Monto"
 },
 "kabuli-chana": {
  "file": "Soaked and dried chickpeas.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Soaked_and_dried_chickpeas.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Tiia Monto"
 },
 "masoor": {
  "file": "Lens culinaris seeds.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Lens_culinaris_seeds.jpg",
  "license": "Public domain",
  "author": "Rainer Zenz at German Wikipedia"
 },
 "urad": {
  "file": "Black gram.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Black_gram.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Sanjay Acharya"
 },
 "moong": {
  "file": "Green Mung Beans.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Green_Mung_Beans.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Sanjay Acharya"
 },
 "tur": {
  "file": "Cajanus cajan MHNT.BOT.2015.2.47.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Cajanus_cajan_MHNT.BOT.2015.2.47.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Roger Culos"
 },
 "soyabean": {
  "file": "Glycine max pod ripe2 Carol Rose (10220373194).jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Glycine_max_pod_ripe2_Carol_Rose_(10220373194).jpg",
  "license": "CC BY 2.0",
  "author": "Harry Rose from South West Rocks, Australia"
 },
 "mustard": {
  "file": "Mustard Seeds (8630655446).jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Mustard_Seeds_(8630655446).jpg",
  "license": "CC BY-SA 2.0",
  "author": "Veganbaking.net from USA"
 },
 "linseed": {
  "file": "Linum usitatissimum seeds, vlaszaden.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Linum_usitatissimum_seeds,_vlaszaden.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Rasbak"
 },
 "til": {
  "file": "Sa white sesame seeds.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Sa_white_sesame_seeds.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Sanjay ach"
 },
 "groundnut": {
  "file": "Roasted Peanuts with shell.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Roasted_Peanuts_with_shell.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Sanjay Acharya"
 },
 "garlic": {
  "file": "Garlic bulbs and cloves.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Garlic_bulbs_and_cloves.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Ivar Leidus"
 },
 "coriander-seed": {
  "file": "Coriander Seeds.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Coriander_Seeds.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Sanjay Acharya"
 },
 "methi-seed": {
  "file": "Fenugreek seeds(মেথি).JPG",
  "url": "https://commons.wikimedia.org/wiki/File:Fenugreek_seeds(%E0%A6%AE%E0%A7%87%E0%A6%A5%E0%A6%BF).JPG",
  "license": "CC BY-SA 4.0",
  "author": "Atudu"
 },
 "dry-chilli": {
  "file": "Dried chillies 4.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Dried_chillies_4.jpg",
  "license": "CC BY 2.0",
  "author": "Richard Mortel"
 },
 "ajwain": {
  "file": "Trachyspermum ammi-1-xavier cottage-yercaud-salem-India.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Trachyspermum_ammi-1-xavier_cottage-yercaud-salem-India.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Yercaud-elango"
 },
 "dry-ginger": {
  "file": "Dried ginger slices (1).jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Dried_ginger_slices_(1).jpg",
  "license": "CC0",
  "author": "Fumikas Sagisavas"
 },
 "isabgol": {
  "file": "Psyllium seed husk pile.JPG",
  "url": "https://commons.wikimedia.org/wiki/File:Psyllium_seed_husk_pile.JPG",
  "license": "CC BY-SA 3.0",
  "author": "Bastique (Cary Bass)"
 },
 "ashwagandha": {
  "file": "Ashwagandha Roots.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Ashwagandha_Roots.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Piyush Kothari"
 },
 "kalonji": {
  "file": "Nigella Sativa seed.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Nigella_Sativa_seed.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Afifa Afrin"
 },
 "poppy-seed": {
  "file": "Poppy seeds for sale in West Bengal, India.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Poppy_seeds_for_sale_in_West_Bengal,_India.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Billjones94"
 },
 "onion": {
  "file": "Red Onions.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Red_Onions.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Gaurav Dhwaj Khadka"
 },
 "potato": {
  "file": "Solanum tuberosum Red Scarlett20170523 7825.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Solanum_tuberosum_Red_Scarlett20170523_7825.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Bff"
 },
 "tomato": {
  "file": "Tomato je.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg",
  "license": "CC BY-SA 3.0",
  "author": "Softeis"
 },
 "coriander-leaves": {
  "file": "Bunches of coriander leaves.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Bunches_of_coriander_leaves.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Kpsudeep"
 },
 "methi-leaves": {
  "file": "Washed fenugreek leaves for cooking methi-chadachadi.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Washed_fenugreek_leaves_for_cooking_methi-chadachadi.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Subhashish Panigrahi"
 },
 "cauliflower": {
  "file": "Stack of cauliflower heads.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Stack_of_cauliflower_heads.jpg",
  "license": "CC0",
  "author": "Jeffery Martin"
 },
 "cabbage": {
  "file": "Fresh Cabbage vegetables.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Fresh_Cabbage_vegetables.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Hajia Hijjah"
 },
 "bhindi": {
  "file": "Bucket of raw okra pods.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Bucket_of_raw_okra_pods.jpg",
  "license": "Public domain",
  "author": "Bill Tarpenning"
 },
 "green-chilli": {
  "file": "Green chillies variety.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Green_chillies_variety.jpg",
  "license": "CC BY-SA 4.0",
  "author": "Medhi jyoti"
 },
 "brinjal": {
  "file": "Eggplant 3.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Eggplant_3.jpg",
  "license": "CC BY-SA 4.0",
  "author": "GTSPACE"
 },
 "bottle-gourd": {
  "file": "Lagenaria siceraria baby fruit.jpeg",
  "url": "https://commons.wikimedia.org/wiki/File:Lagenaria_siceraria_baby_fruit.jpeg",
  "license": "CC BY-SA 4.0",
  "author": "— TBhagat (talk)"
 },
 "bitter-gourd": {
  "file": "U-shaped karela 2017 A.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:U-shaped_karela_2017_A.jpg",
  "license": "CC0",
  "author": "Fructibus"
 },
 "green-peas": {
  "file": "Green pea pods.jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Green_pea_pods.jpg",
  "license": "CC0",
  "author": "Fumikas Sagisavas"
 },
 "orange": {
  "file": "Mandarin Oranges (Citrus Reticulata).jpg",
  "url": "https://commons.wikimedia.org/wiki/File:Mandarin_Oranges_(Citrus_Reticulata).jpg",
  "license": "CC BY-SA 3.0",
  "author": "Joe Ravi"
 }
};
