// All UI text, in English and Hindi. Pick a table with `dict(lang)`.
import type { Lang } from './session';

const en = {
  appName: 'Fasal Bazar',
  appNameHi: 'फसल बाज़ार',
  tagline: 'Today’s mandi prices near you',
  settings: 'Settings',
  district: 'District',
  homeDistrict: 'Home district',
  favouriteCrops: 'Favourite crops',
  favouriteHint: 'Shown first. Pick any.',
  language: 'Language',
  save: 'Save',
  saved: 'Saved',
  market: 'Mandi',
  price: 'Price ₹/qtl',
  change: 'Change',
  msp: 'MSP',
  mspNone: 'No MSP for this crop',
  vsMsp: 'vs MSP',
  vs: 'vs',
  perQuintal: '₹ per quintal (100 kg)',
  noData: 'No prices reported for this crop in this district yet.',
  noDataHint: 'Prices are collected daily.',
  olderReports: 'Older reports',
  history: 'Price history',
  historyHint: 'Tap mandis to compare.',
  mspLine: 'Dashed line = MSP.',
  historyEmpty: 'Not enough history yet.',
  monthlyAvg: 'Monthly averages',
  rangeNames: '3 months|1 year|5 years|All years',
  avgAll: 'Average of all mandis',
  avgIn: 'Average in {d}',
  lastUpdated: 'Data updated',
  latestReport: 'Latest mandi report',
  lastFailed: 'last attempt failed',
  never: 'never',
  source: 'Price is the modal (most common) price, weighted by arrivals across varieties.',
  madeBy: 'Made by Vivek Patidar',
  loading: 'Loading…',
  // price page (v2)
  chooseCrop: 'Crop',
  arrivals: 'Arrivals',
  tonnes: 't',
  up: 'up',
  down: 'down',
  same: 'same as last time',
  sinceLast: 'since last price',
  firstPrice: 'first price',
  today: 'Today',
  yesterday: 'Yesterday',
  daysAgo: '{n} days ago',
  olderPrices: 'Older prices (not reported recently)',
  weekUp: 'Prices are up ₹{n} from last week',
  weekDown: 'Prices are down ₹{n} from last week',
  weekSame: 'Prices are about the same as last week',
  range: 'Range',
  // analysis page
  prices: 'Prices',
  analysis: 'Analysis',
  seeAnalysis: 'See price analysis',
  backToPrices: 'Back to prices',
  isGoodQ: 'Is today’s price good?',
  verdictGood: 'Good price',
  verdictNormal: 'Normal price',
  verdictWeak: 'Weak price',
  verdictHint: 'Compared with the average of the last 30 days.',
  aboutSame: 'about the same',
  districtAvg: 'District average',
  last30: 'Last 30 days average',
  lastYear: 'Same time last year',
  bestMandi: 'Best mandi',
  aboveAvg: '₹{n} above the average',
  compareMandis: 'Mandi comparison',
  dayRange: 'Lowest–highest',
  arrivalsTitle: 'Arrivals',
  tabPrice: 'Price',
  tabArrivals: 'Arrivals',
  arrTrendTitle: 'Arrivals and price, week by week',
  arrTrendHint: 'Bars = tonnes that arrived each week. Line = average price that week.',
  arrPeak: 'Most arrivals: week of {w} ({n} t, avg {p})',
  arrPeakMonth: 'Most arrivals: {w} ({n} t, avg {p})',
  arrMonthly: 'Month by month: total arrivals and average price per month.',
  arrLastWeek: 'Last week: {n} t',
  arrShareTitle: 'Arrivals by mandi (last 30 days)',
  arrShareHint: 'Bigger mandis have more buyers, so prices are usually steadier.',
  arrNone: 'No arrivals reported in this period.',
  arrivalsMore: 'Arrivals are {p}% higher than normal ({today} t, usually {normal} t). Heavy arrivals often push prices down.',
  arrivalsMany: 'Arrivals are about {x} times normal ({today} t, usually {normal} t). Heavy arrivals often push prices down.',
  arrivalsLess: 'Arrivals are {p}% lower than normal ({today} t, usually {normal} t). Low arrivals often support prices.',
  arrivalsNormal: 'Arrivals are normal ({today} t).',
  seasonTitle: 'Which months usually pay best',
  seasonBest: 'Usually best: {months}',
  seasonHint: 'Based on the last {n} years. Each bar shows how that month compares with the year’s average.',
  notEnough: 'Not enough data yet.',
  disclaimer: 'Based on past prices. Not a guarantee of future prices.',
  // crop-first
  crops: 'Price',
  whichCrop: 'Which crop’s price do you want to see?',
  whichCropAnalysis: 'Which crop do you want to analyse?',
  searchCrop: 'Search: wheat, chana, garlic…',
  myCrops: 'My crops',
  allCrops: 'All crops',
  noCropFound: 'No crop found.',
  noRecent: 'No recent prices',
  upTo: 'up to ₹{n}',
  mandisN: '{n} mandis',
  allDistricts: 'All',
  myDistrict: 'My district',
  yourDistrict: 'Your district',
  showAllN: 'Show all {n} mandis',
  showLess: 'Show fewer',
  highestFirst: 'highest price first',
  groupNames: 'Cereals|Pulses|Oilseeds|Spices|Vegetables|Fruits',
  pickFavHint: 'Tap to add or remove. Your crops are shown first.',
  marketWatchTitle: 'Mandi changes on Agmarknet',
  marketWatchNew: 'New mandi: {name} (district {d}), first seen {date}. Its prices are already being stored; add it to scripts/gen-master.ts with a Hindi name to show it in the app.',
  marketWatchMissing: 'Mandi id {id} is in our list but no longer on Agmarknet.',
  marketWatchRenamed: 'Mandi id {id} renamed: "{from}" → "{to}".',
  marketWatchOk: 'No new or missing mandis (checked {date}).',
  cropWatchTitle: 'Other crops trading in our mandis',
  cropWatchHint: 'Not on the curated list. Days seen since tracking began.',
  photoCredits: 'Photo credits',
  creditsIntro: 'Crop photos are from Wikimedia Commons, used under their free licences.',
  // auth
  yourName: 'Your name',
  nameHint: 'In Hindi or English',
  pin: 'PIN',
  pinHint: '4 numbers you will remember. Don’t tell anyone.',
  pin2: 'Enter the same PIN again',
  errName: 'Write your name.',
  errPin: 'PIN must be exactly 4 numbers.',
  errPin2: 'The two PINs don’t match.',
  mobileLabel: 'Mobile',
  login: 'Log in',
  logout: 'Log out',
  signup: 'Create account',
  username: 'User ID',
  usernameHint: '3–20 letters or numbers, e.g. ramesh01',
  password: 'Password',
  passwordHint: 'At least 6 characters',
  phone: 'Mobile number',
  phoneHint: '10-digit mobile number',
  haveAccount: 'Already have an account?',
  noAccount: 'New here?',
  privacy: 'Your number is only used to verify and contact you about this app.',
  errInvalid: 'Wrong mobile number or PIN.',
  errPending: 'Your account is waiting for approval. Please try again later.',
  errRejected: 'Your account request was not approved.',
  errBlocked: 'Your account has been blocked. Contact the admin.',
  errLocked: 'Too many wrong tries. Try again in 30 minutes.',
  errTaken: 'This mobile number already has an account. Please log in.',
  errUsername: 'User ID: 3–20 small letters, numbers or _',
  errPassword: 'Password must be at least 6 characters.',
  errPhone: 'Enter a valid 10-digit mobile number.',
  errDistrict: 'Choose your district.',
  signupDone: 'Request sent! You can log in once the admin approves your account.',
  // admin
  admin: 'Admin',
  users: 'Users',
  pending: 'Waiting for approval',
  approved: 'Approved',
  rejected: 'Rejected',
  blocked: 'Blocked',
  approve: 'Approve',
  reject: 'Reject',
  block: 'Block',
  unblock: 'Unblock',
  resetPassword: 'Set new PIN',
  newPassword: 'New 4-digit PIN',
  joined: 'Joined',
  lastSeen: 'Last seen',
  daysUsed: 'Days used',
  none: 'None',
  dataRefresh: 'Data refresh',
  refreshNow: 'Refresh prices now',
  refreshing: 'Refreshing… (takes about 2 minutes)',
};

export type Strings = typeof en;

const hi: Strings = {
  appName: 'फसल बाज़ार',
  appNameHi: 'Fasal Bazar',
  tagline: 'आपके पास की मंडियों के आज के भाव',
  settings: 'सेटिंग',
  district: 'ज़िला',
  homeDistrict: 'आपका ज़िला',
  favouriteCrops: 'पसंदीदा फसलें',
  favouriteHint: 'ये सबसे पहले दिखेंगी।',
  language: 'भाषा',
  save: 'सेव करें',
  saved: 'सेव हो गया',
  market: 'मंडी',
  price: 'भाव ₹/क्विंटल',
  change: 'बदलाव',
  msp: 'MSP (समर्थन मूल्य)',
  mspNone: 'इस फसल का MSP नहीं है',
  vsMsp: 'MSP से',
  vs: 'पिछला',
  perQuintal: '₹ प्रति क्विंटल (100 किलो)',
  noData: 'इस ज़िले में अभी इस फसल का भाव नहीं आया है।',
  noDataHint: 'भाव रोज़ अपडेट होते हैं।',
  olderReports: 'पुराने भाव',
  history: 'भाव का इतिहास',
  historyHint: 'मंडियों की तुलना के लिए छुएँ।',
  mspLine: 'डैश लाइन = MSP',
  historyEmpty: 'अभी पर्याप्त इतिहास नहीं है।',
  monthlyAvg: 'महीने का औसत',
  rangeNames: '3 महीने|1 साल|5 साल|सभी साल',
  avgAll: 'सभी मंडियों का औसत',
  avgIn: '{d} का औसत',
  lastUpdated: 'डेटा अपडेट',
  latestReport: 'मंडी का ताज़ा भाव',
  lastFailed: 'पिछली कोशिश विफल',
  never: 'कभी नहीं',
  source: 'भाव = मॉडल (सबसे आम) भाव, सभी किस्मों की आवक के अनुसार।',
  madeBy: 'बनाया: विवेक पाटीदार',
  loading: 'लोड हो रहा है…',
  chooseCrop: 'फसल',
  arrivals: 'आवक',
  tonnes: 'टन',
  up: 'ज़्यादा',
  down: 'कम',
  same: 'पिछले भाव जितना',
  sinceLast: 'पिछले भाव से',
  firstPrice: 'पहला भाव',
  today: 'आज',
  yesterday: 'कल',
  daysAgo: '{n} दिन पहले',
  olderPrices: 'पुराने भाव (हाल में नहीं आए)',
  weekUp: 'पिछले हफ़्ते से भाव ₹{n} बढ़े',
  weekDown: 'पिछले हफ़्ते से भाव ₹{n} घटे',
  weekSame: 'भाव पिछले हफ़्ते जितने ही हैं',
  range: 'दायरा',
  prices: 'भाव',
  analysis: 'विश्लेषण',
  seeAnalysis: 'भाव का विश्लेषण देखें',
  backToPrices: 'भाव पर वापस',
  isGoodQ: 'क्या आज का भाव अच्छा है?',
  verdictGood: 'अच्छा भाव',
  verdictNormal: 'सामान्य भाव',
  verdictWeak: 'कमज़ोर भाव',
  verdictHint: 'पिछले 30 दिनों के औसत से तुलना।',
  aboutSame: 'लगभग बराबर',
  districtAvg: 'ज़िले का औसत',
  last30: 'पिछले 30 दिन का औसत',
  lastYear: 'पिछले साल इसी समय',
  bestMandi: 'सबसे अच्छी मंडी',
  aboveAvg: 'औसत से ₹{n} ज़्यादा',
  compareMandis: 'मंडियों की तुलना',
  dayRange: 'सबसे कम–ज़्यादा',
  arrivalsTitle: 'आवक',
  tabPrice: 'भाव',
  tabArrivals: 'आवक',
  arrTrendTitle: 'हर हफ़्ते की आवक और भाव',
  arrTrendHint: 'खंभे = उस हफ़्ते आई फसल (टन)। लाइन = उस हफ़्ते का औसत भाव।',
  arrPeak: 'सबसे ज़्यादा आवक: {w} वाला हफ़्ता ({n} टन, औसत {p})',
  arrPeakMonth: 'सबसे ज़्यादा आवक: {w} ({n} टन, औसत {p})',
  arrMonthly: 'महीने के हिसाब से: हर महीने की कुल आवक और औसत भाव।',
  arrLastWeek: 'पिछला हफ़्ता: {n} टन',
  arrShareTitle: 'किस मंडी में कितनी आवक (पिछले 30 दिन)',
  arrShareHint: 'बड़ी मंडी में खरीदार ज़्यादा होते हैं, इसलिए भाव अक्सर ज़्यादा स्थिर रहते हैं।',
  arrNone: 'इस समय में कोई आवक दर्ज नहीं हुई।',
  arrivalsMore: 'आवक सामान्य से {p}% ज़्यादा है ({today} टन, आम तौर पर {normal} टन)। ज़्यादा आवक से अक्सर भाव गिरते हैं।',
  arrivalsMany: 'आवक सामान्य से लगभग {x} गुना है ({today} टन, आम तौर पर {normal} टन)। ज़्यादा आवक से अक्सर भाव गिरते हैं।',
  arrivalsLess: 'आवक सामान्य से {p}% कम है ({today} टन, आम तौर पर {normal} टन)। कम आवक से अक्सर भाव को सहारा मिलता है।',
  arrivalsNormal: 'आवक सामान्य है ({today} टन)।',
  seasonTitle: 'किन महीनों में भाव अच्छे रहते हैं',
  seasonBest: 'आम तौर पर सबसे अच्छे: {months}',
  seasonHint: 'पिछले {n} साल के आधार पर। हर पट्टी बताती है कि वह महीना साल के औसत से कितना ऊपर या नीचे रहा।',
  notEnough: 'अभी पर्याप्त डेटा नहीं है।',
  disclaimer: 'यह पुराने भावों पर आधारित है, आगे के भाव की गारंटी नहीं।',
  crops: 'भाव',
  whichCrop: 'किस फसल का भाव देखना है?',
  whichCropAnalysis: 'किस फसल का विश्लेषण देखना है?',
  searchCrop: 'खोजें: गेहूं, चना, लहसुन…',
  myCrops: 'मेरी फसलें',
  allCrops: 'सभी फसलें',
  noCropFound: 'कोई फसल नहीं मिली।',
  noRecent: 'हाल में भाव नहीं',
  upTo: '₹{n} तक',
  mandisN: '{n} मंडी',
  allDistricts: 'सभी',
  myDistrict: 'मेरा ज़िला',
  yourDistrict: 'आपका ज़िला',
  showAllN: 'सभी {n} मंडियां दिखाएं',
  showLess: 'कम दिखाएं',
  highestFirst: 'सबसे ज़्यादा भाव पहले',
  groupNames: 'अनाज|दालें|तिलहन|मसाले|सब्ज़ियां|फल',
  pickFavHint: 'जोड़ने या हटाने के लिए छुएँ। आपकी फसलें सबसे पहले दिखेंगी।',
  marketWatchTitle: 'एगमार्कनेट पर मंडी बदलाव',
  marketWatchNew: 'नई मंडी: {name} (ज़िला {d}), पहली बार {date}। इसके भाव सेव हो रहे हैं; ऐप में दिखाने के लिए scripts/gen-master.ts में हिंदी नाम के साथ जोड़ें।',
  marketWatchMissing: 'मंडी id {id} हमारी सूची में है पर एगमार्कनेट पर नहीं।',
  marketWatchRenamed: 'मंडी id {id} का नाम बदला: "{from}" → "{to}"।',
  marketWatchOk: 'कोई नई या गायब मंडी नहीं ({date} को जांचा)।',
  cropWatchTitle: 'हमारी मंडियों में बिक रही दूसरी फसलें',
  cropWatchHint: 'चुनी हुई सूची में नहीं। ट्रैकिंग शुरू होने से अब तक कितने दिन दिखीं।',
  photoCredits: 'फोटो स्रोत',
  creditsIntro: 'फसलों की फोटो विकिमीडिया कॉमन्स से हैं, उनके मुफ़्त लाइसेंस के तहत।',
  yourName: 'आपका नाम',
  nameHint: 'हिंदी या अंग्रेज़ी में',
  pin: 'PIN',
  pinHint: '4 अंक जो आपको याद रहें। किसी को न बताएं।',
  pin2: 'वही PIN दोबारा डालें',
  errName: 'अपना नाम लिखें।',
  errPin: 'PIN ठीक 4 अंकों का होना चाहिए।',
  errPin2: 'दोनों PIN एक जैसे नहीं हैं।',
  mobileLabel: 'मोबाइल',
  login: 'लॉग इन',
  logout: 'लॉग आउट',
  signup: 'नया खाता बनाएँ',
  username: 'यूज़र आईडी',
  usernameHint: '3–20 अक्षर या अंक, जैसे ramesh01',
  password: 'पासवर्ड',
  passwordHint: 'कम से कम 6 अक्षर',
  phone: 'मोबाइल नंबर',
  phoneHint: '10 अंकों का मोबाइल नंबर',
  haveAccount: 'पहले से खाता है?',
  noAccount: 'नए हैं?',
  privacy: 'आपका नंबर सिर्फ़ पहचान और इस ऐप के बारे में संपर्क के लिए है।',
  errInvalid: 'मोबाइल नंबर या PIN गलत है।',
  errPending: 'आपका खाता मंज़ूरी का इंतज़ार कर रहा है। थोड़ी देर बाद कोशिश करें।',
  errRejected: 'आपके खाते का अनुरोध मंज़ूर नहीं हुआ।',
  errBlocked: 'आपका खाता बंद कर दिया गया है। एडमिन से संपर्क करें।',
  errLocked: 'बहुत बार गलत PIN। 30 मिनट बाद फिर कोशिश करें।',
  errTaken: 'इस मोबाइल नंबर का खाता पहले से है। लॉग इन करें।',
  errUsername: 'यूज़र आईडी: 3–20 छोटे अंग्रेज़ी अक्षर, अंक या _',
  errPassword: 'पासवर्ड कम से कम 6 अक्षर का हो।',
  errPhone: 'सही 10 अंकों का मोबाइल नंबर डालें।',
  errDistrict: 'अपना ज़िला चुनें।',
  signupDone: 'अनुरोध भेज दिया! एडमिन की मंज़ूरी के बाद आप लॉग इन कर पाएँगे।',
  admin: 'एडमिन',
  users: 'यूज़र',
  pending: 'मंज़ूरी बाकी',
  approved: 'मंज़ूर',
  rejected: 'नामंज़ूर',
  blocked: 'बंद',
  approve: 'मंज़ूर करें',
  reject: 'नामंज़ूर करें',
  block: 'बंद करें',
  unblock: 'फिर से चालू करें',
  resetPassword: 'नया PIN सेट करें',
  newPassword: 'नया 4 अंकों का PIN',
  joined: 'जुड़े',
  lastSeen: 'आखिरी बार',
  daysUsed: 'कितने दिन',
  none: 'कोई नहीं',
  dataRefresh: 'डेटा रिफ्रेश',
  refreshNow: 'अभी भाव रिफ्रेश करें',
  refreshing: 'रिफ्रेश हो रहा है… (लगभग 2 मिनट)',
};

const TABLES: Record<Lang, Strings> = { en, hi };
export const dict = (lang: Lang): Strings => TABLES[lang] ?? en;

export const MONTH_NAMES: Record<Lang, string[]> = {
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  hi: ['जनवरी', 'फ़रवरी', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अगस्त', 'सितंबर', 'अक्टूबर', 'नवंबर', 'दिसंबर'],
};

export const MONTH_SHORT: Record<Lang, string[]> = {
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  hi: ['जन', 'फ़र', 'मार्च', 'अप्रै', 'मई', 'जून', 'जुला', 'अग', 'सित', 'अक्टू', 'नव', 'दिस'],
};

/** Fill "{n}" placeholders. */
export const fill = (template: string, vars: Record<string, string | number>) =>
  template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));

/** Crop/district display name in the user's language. */
export const nameIn = (x: { en: string; hi?: string }, lang: Lang) => (lang === 'hi' && x.hi ? x.hi : x.en);
